version: '3'
services:
  alertmanager:
    image: prom/alertmanager:v0.15.1
    volumes:
      - "./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      # - alertmanager-storage:/alertmanager
    ports:
      - "9093:9093"
  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    volumes:
      - "./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml"
    ports:
      - "9115:9115"
  prometheus:
    image: prom/prometheus:v2.3.2
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      # - prometheus-storage:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:5.2.2
    ports:
      - "3000:3000"
# volumes:
#   - alertmanager-storage:
#   - prometheus-storage:
